### PR TITLE
Expand docs carolin

### PR DESCRIPTION
**Pull request by carolinthomas**
I have started writing the first draft for the documentation. 
For that, I changed the `wgan.py` file to hide the title and the attributes in the documentation.

### CODE REVIEW

**Comment by evanmunro** [comment]
I've pushed some commits with some updates to the content. 

In addition, could you address the following before we merge? 
- Can we make the homepage the Introduction rather than index.html? Probably can just make the introduction page the index.html 
- Make sure that all references in the text to code functions are links to the API, rather than code formats. Ex. in introduction.rst, DataWrapper.apply_generator. In setting up the data: `pre_process`, etc. I wasn't sure how to do this myself. 
- Let's combine the Training Models and Generating Data section into one page since both are a little sparse 

Thanks for the great work!

**Comment by evanmunro** [comment]
Also, @Jonas-Metzger if you want, take a look at the current state of the docs in this branch and let us know if you have any comments or changes: (to generate them from source run `make html` in the docs folder, need a few extra python packages).

**Comment by carolinthomas** [comment]
@evanmunro I have changed the issues you addressed [above](https://github.com/gsbDBI/ds-wgan/pull/7#issuecomment-552227888).

**Comment by evanmunro** [comment]
still doesn't look quite right: when I click on Home, I don't need table of contents to appear both on the left sidebar and in the index.html. Right now Introduction only appears in the sidebar when I click on Home; if I click on one of the other sections it disappears from the sidebar.

**Comment by carolinthomas** [comment]
@evanmunro  As far as I understand it, we need the table of contents in index.rst to create the sidebar, but I can double-check. 
I never have "Introduction" on the sidebar (please see the Screenshot), so do you want it included in the sidebar or not (I am not sure if we can include it)

Screen Shot 2019-11-11 at 10 58 01 AM

**Comment by carolinthomas** [comment]
@evanmunro I solved the issue with the table of content. Now, we only have a sidebar.

**Review by evanmunro — APPROVED** [review]
first draft of docs is ready to merge

**Pull request merged**
